title: "dps.ai"
author: "Dhruv Pratap Singh"
description: "Everything AI"
more: "read more »"
url: "https://dhruvpratapsingh.github.io"
baseurl: ""
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # end excerpt with two blank lines

archive_is_homepage: true # shows archive instead of excerpts on the index page
dark: false # enables dark mode

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"

me-img: "https://github.com/dhruvpratapsingh.png?size=500"

navigation: # enables navigation in header
  # - index.html
  - archive.html
  - about.md

favicons: # see http://fontawesome.io/icons/#brand for all possible icons
  - github: "https://github.com/dhruvpratapsingh"
  - stack-overflow: "https://stackoverflow.com/users/5942489/dhruv"
  - medium: "https://medium.com/@dhruv.singh"
  - envelope: "mailto:dhruvpsg@gmail.com"
  - linkedin: "https://www.linkedin.com/in/dhruv-pratap-singh-b918045b"
  #- feed: "feed.xml"

comments: # embed comments
  disqus: "dps-ai"
  # isso: "comments.mysite.org"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate, jekyll-seo-tag]
